# Generated by Django 5.1 on 2024-08-30 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('experiences', models.JSONField()),
                ('skills', models.JSONField()),
                ('resume', models.FileField(blank=True, null=True, upload_to='employee_resumes/')),
                ('portfolio', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pan', models.CharField(max_length=10)),
                ('gsttin', models.CharField(max_length=15)),
                ('url_address', models.URLField()),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to='employer_profiles/')),
            ],
        ),
    ]
