# Generated by Django 5.1 on 2024-08-30 08:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='employer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, validators=[account.models.validate_gstin]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='pan',
            field=models.CharField(blank=True, max_length=10, validators=[account.models.validate_pan]),
        ),
    ]
